export const carColors = [
	{ name: "Alpine White", hex: "#FFFFFF" },
	{ name: "Jet Black", hex: "#000000" },
	{ name: "Mineral Grey", hex: "#4E5754" },
	{ name: "Sapphire Blue", hex: "#0F52BA" },
	{ name: "Racing Red", hex: "#FF2800" },
	{ name: "British Racing Green", hex: "#004225" },
	{ name: "Sunset Orange", hex: "#F56217" },
	{ name: "Glacier Silver", hex: "#C4C4C4" },
	{ name: "Midnight Blue", hex: "#003366" },
	{ name: "Burgundy", hex: "#800020" },
	{ name: "Champagne Gold", hex: "#E6BE8A" },
	{ name: "Gunmetal Grey", hex: "#2C3539" },
	{ name: "Cosmic Purple", hex: "#604D8D" },
	{ name: "Emerald Green", hex: "#046307" },
	{ name: "Candy Red", hex: "#E30022" },
	{ name: "Titanium Silver", hex: "#A7A9AC" },
	{ name: "Mystic Bronze", hex: "#AD8A56" },
	{ name: "Phantom Black", hex: "#0E0E10" },
	{ name: "Ceramic White", hex: "#FCFCFC" },
	{ name: "Lunar Blue", hex: "#354E6B" },
	{ name: "Magnetic Grey", hex: "#5A5A5A" },
	{ name: "Velocity Yellow", hex: "#FEE715" },
	{ name: "Nardo Grey", hex: "#7A7D81" },
	{ name: "Teal Blue", hex: "#367588" },
];
